d={"name":"king","age":15,"percentage":90.13}
print(d)
print(d["age"])
f={"name":"king",15:24,15.60:7838,True:True}
print(len(f))
print(d.get('name'))
d.update({"name":"vaihu"})
print(d)
print(d.keys())
print(d.values())